# GitLab CI/CD pipeline for Spring Boot (Maven)

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn $MAVEN_CLI_OPTS clean compile -Dnet.bytebuddy.experimental=true
  artifacts:
    paths:
      - target/*.jar

unit_test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn $MAVEN_CLI_OPTS test -Dnet.bytebuddy.experimental=true
  dependencies:
    - build
